name: iptv_editor_pro
description: Professional IPTV Playlist Editor with Smart Link Detection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Network
  http: ^1.1.0
  dio: ^5.4.0
  
  # Utils
  clipboard: ^0.1.3
  intl: ^0.18.1
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0a0a0f"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
